# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/'),
        ),
    ]
