# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='expenses.Expense'),
        ),
    ]
